sudo: required
dist: bionic
before_install:
  - sudo apt-get update
  - sudo apt install -y libgirepository1.0-dev gcc libcairo2-dev pkg-config python3-dev python3.8-dev gir1.2-gtk-3.0 
  - sudo apt-get install -y libgstreamer1.0-0 gstreamer1.0-plugins-base gstreamer1.0-plugins-good gstreamer1.0-plugins-bad gstreamer1.0-plugins-ugly gstreamer1.0-libav gstreamer1.0-doc gstreamer1.0-tools gstreamer1.0-x gstreamer1.0-alsa gstreamer1.0-gl gstreamer1.0-gtk3 gstreamer1.0-qt5 gstreamer1.0-pulseaudio
language: python
python:
  - "3.6"
install:
    - pip install tox-travis
script:
    - tox
